version: "3.9"

services:
  datalens-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datalens-proxy
    ports:
      - "3001:80"  # можно поменять порт
    networks:
      parse:
        aliases:
          - datalens-proxy
    restart: unless-stopped

networks:
  parse:
    name: parse
    driver: bridge
    external: true
