version: "3.9"

services:
  datalens-proxy:
    build: .
    container_name: datalens-proxy
    ports:
      - "3100:3100"  # можно поменять порт
    networks:
      parse:
        aliases:
          - datalens-proxy
    restart: unless-stopped

networks:
  parse:
    external: true
